import { NextRequest, NextResponse } from "next/server";
import { prisma } from "../../../../../lib/prisma";
import { supabaseAdmin } from "../../../../../lib/supabase";
import fal from "@fal-ai/client";

// PROMPT TEMPLATE
const BASE_PROMPT = (action: string) =>
    `From this photo, generate the facade renovation involving ${action} ONLY on the wooden parts. It is mandatory that the stone walls, windows, roof, and balconies remain exactly as they are in the original photo. Do not change any structural element.`;

// PROMPTS MAPPING
const MATERIAL_PROMPTS: Record<string, string> = {
    "Sablage Naturel": BASE_PROMPT("sandblasting the wood to a natural light beige finish"),
    "Lasure Chêne Clair": BASE_PROMPT("applying a light oak stain"),
    "Lasure Chêne Foncé": BASE_PROMPT("applying a dark oak stain")
};

export async function POST(
    req: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { id: projectId } = await params;
        const { variationId } = await req.json();

        // 1. Get project and variation
        const project = await prisma.project.findUnique({
            where: { id: projectId },
            include: { variations: true }
        });

        if (!project || !project.originalImage) {
            return NextResponse.json({ error: "Project or original image not found" }, { status: 404 });
        }

        const variation = project.variations.find((v: any) => v.id === variationId);
        if (!variation) {
            return NextResponse.json({ error: "Variation not found" }, { status: 404 });
        }

        // CREDIT PROTECTION: If image already exists, don't re-generate
        if (variation.image) {
            console.log(`AI: Image already exists for ${variation.id}, skipping generation.`);
            return NextResponse.json({ success: true, data: variation });
        }

        const prompt = MATERIAL_PROMPTS[variation.name] || `${variation.name} architectural finish, realistic renovation.`;

        console.log(`AI: Generating for project ${projectId}, variation ${variation.name}`);
        console.log(`AI: Using prompt: ${prompt}`);
        console.log(`AI: Reference image: ${project.originalImage}`);

        // 2. Call Fal.ai
        // Using "gpt-image-1.5/edit" High Fidelity for better structural preservation
        const result: any = await fal.subscribe("fal-ai/gpt-image-1.5/edit", {
            input: {
                prompt: prompt,
                image_urls: [project.originalImage],
                fidelity_to_input_image: "high",
            },
            logs: true,
            onQueueUpdate: (update) => {
                console.log(`AI Queue: ${update.status}`);
            },
        });

        const generatedImageUrl = result.images?.[0]?.url;
        if (!generatedImageUrl) throw new Error("No image generated by AI");
        console.log("AI: Generation success, URL:", generatedImageUrl);

        // 3. Download generated image and upload to Supabase
        const imgRes = await fetch(generatedImageUrl);
        if (!imgRes.ok) throw new Error("Failed to download generated image");
        const arrayBuffer = await imgRes.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);

        const fileName = `${projectId}/${variationId}-${Date.now()}.png`;

        if (!supabaseAdmin) throw new Error("Supabase Admin not available");

        const { data: uploadData, error: uploadError } = await supabaseAdmin.storage
            .from("projects")
            .upload(fileName, buffer, {
                contentType: "image/png",
                upsert: true
            });

        if (uploadError) throw uploadError;

        const { data: { publicUrl } } = supabaseAdmin.storage
            .from("projects")
            .getPublicUrl(fileName);

        // 4. Update Variation in DB
        const updatedVariation = await prisma.variation.update({
            where: { id: variationId },
            data: { image: publicUrl }
        });

        return NextResponse.json({ success: true, data: updatedVariation });

    } catch (error: any) {
        console.error("AI Generation Error:", error);

        // Handle specific API errors
        if (error?.status === 403 || error?.message?.includes("Forbidden")) {
            return NextResponse.json(
                { error: "Paiement requis sur Fal.ai. Veuillez ajouter des crédits." },
                { status: 402 }
            );
        }

        return NextResponse.json(
            { error: "AI Generation failed", details: error?.message },
            { status: 500 }
        );
    }
}
